In [1]:
import numpy as np

In [2]:
print(np)

<module 'numpy' from 'c:\\Users\\KDP-25\\anaconda3\\envs\\PY_39\\lib\\site-packages\\numpy\\__init__.py'>


In [4]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__) != type(np.ndarray.var):
            print(i)

T
all
any
argmax
argmin
argpartition
argsort
astype
base
byteswap
choose
clip
compress
conj
conjugate
copy
ctypes
cumprod
cumsum
data
diagonal
dot
dtype
dump
dumps
fill
flags
flat
flatten
getfield
imag
item
itemset
itemsize
max
mean
min
nbytes
ndim
newbyteorder
nonzero
partition
prod
ptp
put
ravel
real
repeat
reshape
resize
round
searchsorted
setfield
setflags
shape
size
sort
squeeze
std
strides
sum
swapaxes
take
tobytes
tofile
tolist
tostring
trace
transpose
var
view


In [6]:
# 리스트나 튜플에 array함수 사용해서 다차원 배열 생성

i= [1,2,3,4]
a=np.array(i)
print(a)
print(type(a))

t=(1,2,3,4)
b=np.array(t)
type(b)

[1 2 3 4]
<class 'numpy.ndarray'>


numpy.ndarray

In [7]:
# 다차원배열은 메모리에서 데이터 관리-> obj속성으로 접근 가능

print(a.data)
print(a.data.obj)
print(type(a.data.obj))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
# 자료형 지정 가능, 미지정시 내부적으로 결정
e= np.array(i, dtype=np.float64)
print(e, e.dtype)

[1. 2. 3. 4.] float64


In [10]:
# 2차원 배열
# itemsize=> 하나의 원소크기
# strides=> 원소와 하나의 행의 바이트크기

a2= np.array([[1,2,3], [4,5,6]])
print(a2.shape, a2.ndim, a2.dtype, a2.itemsize, 
      a2.size, a2.strides, sep='\n')


(2, 3)
2
int32
4
6
(12, 4)


In [16]:
# 같은 이름의 함수와 메소드
np_=set(dir(np))
nd_= set(dir(np.ndarray))
npd_=np_&nd_
print(len(npd_))

count=0
for i in list(npd_):
    count+=1
    print(i, end=' ')
    if count% 5==0:
        print()

48
swapaxes min sort trace partition 
prod take conjugate ptp conj 
__dir__ ndim cumprod compress put 
repeat __doc__ clip imag mean 
diagonal reshape transpose size shape 
real searchsorted ravel choose std 
nonzero any argmax squeeze argpartition 
argmin nbytes resize dot sum 
dtype var copy argsort cumsum 
all max round 

In [18]:
# 특징-> 반복문을 사용하지 않는 계산(벡터화 연산)
a= dir(np)
np.ufunc
count=0
for i in a:
    if i=='Tester':
        continue
    if type(np.__dict__[i])== np.ufunc:
        print(i, end=' ')
        count+=1
        if count%5== 0:
            print()

abs absolute add arccos arccosh 
arcsin arcsinh arctan arctan2 arctanh 
bitwise_and bitwise_not bitwise_or bitwise_xor cbrt 
ceil conj conjugate copysign cos 
cosh deg2rad degrees divide divmod 
equal exp exp2 expm1 fabs 
float_power floor floor_divide fmax fmin 
fmod frexp gcd greater greater_equal 
heaviside hypot invert isfinite isinf 
isnan isnat lcm ldexp left_shift 
less less_equal log log10 log1p 
log2 logaddexp logaddexp2 logical_and logical_not 
logical_or logical_xor matmul maximum minimum 
mod modf multiply negative nextafter 
not_equal positive power rad2deg radians 
reciprocal remainder right_shift rint sign 
signbit sin sinh spacing sqrt 
square subtract tan tanh 

KeyError: 'testing'

In [19]:
# 벡터화 연산
# -> 배열의 같은 위치의 원소끼리 계산을 자동으로 처리하는 기능
a= np.arange(6,10)
print(a)
b= np.arange(10,14)
print(b)
c=a*b
c  #알어서 일대일 대조후  계산-> 개수 불일치시 에러

[6 7 8 9]
[10 11 12 13]


array([ 60,  77,  96, 117])

In [20]:
# 배열 다른 변수에 할당시 공유 (수정시 원본도 수정됨)
a= np.array([[1,2], [3,4]])
b=a
b[0]=999
print(a, b, sep='\n')

[[999 999]
 [  3   4]]
[[999 999]
 [  3   4]]


In [21]:
# 다른 메모리 할당-> copy사용
f= np.array([4,5,6,7,8])
e=f.copy()
np.shares_memory(f,e)

False

In [24]:
# 리스트검색 list[i]= list.__getitem__(i) 와 동일
# i에는 값, 인덱스, 논리 등 가능
# 인덱스 슬라이싱도 slice(a,b)와 동일
i= list(range(1,10))
print(i.__getitem__(slice(1,3)))
i[1:3]

[2, 3]


[2, 3]

In [25]:
# scalar-> 0차원(단일원소)
# shape 없음
a=np.array(43)
print(a.ndim, a.shape)

0 ()


In [27]:
# vector-> 1차원
v= np.array([43])
print(v.ndim, v.shape)

1 (1,)


In [30]:
# np.arrage()
# range()함수와 동일
v1= np.arange(10.5, 20.5, 0.5)
print(v1, v1.dtype, v1.size)

[10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5 17.
 17.5 18.  18.5 19.  19.5 20. ] float64 20


In [ ]:
# np.linspace(시작, 끝, 총원소개수)
# 총 원소의 개수에 맞춰서 배열 생성
# endpoint= 끝 포함여부, retstep= 간격보여주기
lal= np.linspace(1,10,10, endpoint=False, retstep=True)

In [31]:
# ppt.36
# 벡터 크기-> linalg 모듈, norm 함수 사용
v=np.arange(3,5)
np.linalg.norm(v)

5.0

In [33]:
# 표준 단위벡터-> ei => i에 해당하는 인덱스의 원소만 1로 가짐
e1= np.array([1,0,0])
print(np.linalg.norm(e1))

e3=np.array([0,0,1])
np.linalg.norm(e3)

1.0


1.0

In [34]:
# 단위벡터 -> 정규화벡터 크기/벡터 원소

v_3= np.array([1,2,3])
v_3_n= np.linalg.norm(v_3)
v_3_u= v_3/ v_3_n

np.linalg.norm(v_3_u)


1.0

In [35]:
# 벡터의 상등-> 방향과 크기가 같다

In [37]:
# 두 벡터의 거리-> 벡터 차^2의 합의 제곱근

c=np.arange(10,13)
d=np.arange(0,3)
np.sqrt(np.sum(np.square(c-d)))
np.linalg.norm(c-d)


17.320508075688775

### 행렬

In [39]:
# 2차월 배열을 통해 생성
A= np.array([[43], [44]])
print(A.ndim, A.shape)

2 (2, 1)


In [40]:
# 행렬랭크-> 내부 벡터의 조합으로 구성할 수 없는 벡터의 개수

c1= np.array([[1,2,4], [2,4,8], [3,4,5]])
np.linalg.matrix_rank(c1)

2

In [41]:
# 차원 확장
x=np.array([1,2])
y=np.expand_dims(x, axis=1)
print(y)

[[1]
 [2]]


In [42]:
# 차원 축소

x= np.array([[1,4,5], [4,5,6], [7,8,9]])
print(x.flatten())
print(x.ravel())

[1 4 5 4 5 6 7 8 9]
[1 4 5 4 5 6 7 8 9]


In [ ]:
# 정사각행렬
