In [1]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv(r'C:\Users\KDP-25\Desktop\KDT_06\numpy\Day01\예제소스코드모음1\data\ch2_scores_em.csv')

df.head()

student number  english  mathematics
0               1       42           65
1               2       69           80
2               3       56           63
3               4       41           63
4               5       57           76

In [4]:
scores= np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [6]:
print(sum(scores/len(scores)))
print(np.mean(scores))
print(df.mean())
print(np.sort(scores))

55.0
55.0
student number    25.50
english           58.38
mathematics       78.88
dtype: float64
[41 42 48 49 56 57 58 65 65 69]


In [7]:
sorted_scores= np.sort(scores)
n=len(sorted_scores)
if n%2== 0:
    m0= sorted_scores[n//2-1]
    m1= sorted_scores[n//2]
    median= (m0+ m1)/2
else:
    median= sorted_scores[(n+1)//2-1]

print(median)

56.5


In [8]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [10]:
# 편차
mean= np.mean(scores)
deviation= scores- mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [14]:
# 편차 비교
scores_df= pd.DataFrame({'score':scores},
                        index=pd.Index(['A','B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
                                       name='student'))
summary_df= scores_df.copy()
summary_df['deviation']= deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [15]:
#편차의 합은 항상 0
summary_df.mean()

score        55.0
deviation     0.0
dtype: float64

In [17]:
#분산
print(np.var(scores))
np.mean(deviation**2)


86.0


86.0

In [18]:
summary_df['square of deviation']= np.square(deviation)
summary_df

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

In [19]:
summary_df.mean()

score                  55.0
deviation               0.0
square of deviation    86.0
dtype: float64

In [20]:
np.sqrt(np.var(scores, ddof=0))
np.std(scores, ddof=0)

9.273618495495704

In [22]:
print(np.max(scores) - np.min(scores))
print(pd.Series(scores).describe())



28
count    10.000000
mean     55.000000
std       9.775252
min      41.000000
25%      48.250000
50%      56.500000
75%      63.250000
max      69.000000
dtype: float64


In [23]:
scores_Q1= np.percentile(scores, 25)
scores_Q3= np.percentile(scores, 75)
scores_IQR= scores_Q3-scores_Q1
scores_IQR

15.0

In [33]:
# 정규화 
# pd.set_option(pat='precision',val= 3)
#소수점 제한
z= (scores- np.mean(scores))/np.std(scores)
print(z, np.mean(z), np.std(z, ddof=0), sep='\n')

[-1.402  1.51   0.108 -1.51   0.216 -0.755  1.078 -0.647  1.078  0.323]
-1.6653345369377347e-17
0.9999999999999999


In [36]:
english_scores= np.array(df['english'])
pd.Series(english_scores).describe()

count    50.000000
mean     58.380000
std       9.799813
min      37.000000
25%      54.000000
50%      57.500000
75%      65.000000
max      79.000000
dtype: float64

In [40]:
#도수분포표 생성
freq, _= np.histogram(english_scores, bins=10, range=(0,100))
# 빈도가 10인 히스토그램 array 생성
freq_class= [f'{i}~{i+10}' for i in range(0,100,10)]
# 빈도 index 생성
freq_dist_df= pd.DataFrame({'frequency':freq},
                          index=pd.Index(freq_class,
                                          name='class'))
freq_dist_df

frequency
class            
0~10            0
10~20           0
20~30           0
30~40           2
40~50           8
50~60          16
60~70          18
70~80           6
80~90           0
90~100          0

In [45]:
# 계급값 -> 각 계급의 중앙값 사용
class_value= [(i+(i+10))//2 for i in range(0, 100, 10)]
class_value

[5, 15, 25, 35, 45, 55, 65, 75, 85, 95]

In [42]:
rel_freq= freq/ freq.sum()
rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.16, 0.32, 0.36, 0.12, 0.  , 0.  ])

In [43]:
cum_rel_freq= np.cumsum(rel_freq)
cum_rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.2 , 0.52, 0.88, 1.  , 1.  , 1.  ])

In [46]:
freq_dist_df['class value']= class_value
freq_dist_df['relative frequency']= rel_freq
freq_dist_df['cumulative relative frequency']= cum_rel_freq
freq_dist_df= freq_dist_df[['class value', 'freqency', 
                            'relative frequency', 'cumulative relative frequency']]

KeyError: "['freqency'] not in index"