### 내부 조작 함수

In [3]:
import numpy as np


In [1]:
# 원소 기준 정렬-> sort, np.sort

In [6]:
# numpy.argsort-> 원소 기준 정렬한 것을 인덱스로 보여줌
bb= np.linspace(1,6,6, dtype=np.int32)
np.random.shuffle(bb)
print(bb)
np.argsort(bb) 
#-> 기존 데이터를 바꾸지 않고 카피하는 수고를 덜어줌

[6 2 1 3 4 5]


array([2, 1, 3, 4, 5, 0], dtype=int64)

In [8]:
# 배열 값 변경
#모든 원소가 1인 배열 생성
o= np.ones(10)
print(o)

#값 변경
o.fill(100)
print(o)

#원하는 동일한 수로 이루어진 배열 생성
a= np.full(o.shape, 99.)
a

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]


array([99., 99., 99., 99., 99., 99., 99., 99., 99., 99.])

In [12]:
# 위치변경 및 이동
array= np.arange(4).reshape((2,2))
print(array)
# 좌우 반전 (lr)
print(np.fliplr(array))
# 상하 반전 (ud)
print(np.flipud(array))
# 회전
np.rot90(array,1) #반시계, 90도



[[0 1]
 [2 3]]
[[1 0]
 [3 2]]
[[2 3]
 [0 1]]


array([[1, 3],
       [0, 2]])

In [13]:
# 원소 점검
m= np.random.randn(3,5)
print(m)
# 실수 확인
np.isreal(m)
# 무한대 확인
np.isinf(m)
# nan 확인
np.isnan(m)

[[-1.48453101  0.01416405 -2.47769815 -1.90545283 -0.31149176]
 [-2.43987736 -0.37562139 -0.53226058 -0.54137433 -0.1969662 ]
 [-0.16588053  0.59690686  0.41603297  0.85571745 -1.42728333]]


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

### padding 처리

In [16]:
# 패딩
# 기존 배열 밖에 원소 붙여서 배열 확장
x= np.arange(1,5).reshape(2,2)
print(x)
z= np.zeros((3,3))
z[:2, :2]=x
print(z)

[[1 2]
 [3 4]]
[[1. 2. 0.]
 [3. 4. 0.]
 [0. 0. 0.]]


In [19]:
# 패딩 함수-> pad
print(np.pad(x,(0,1), 'constant')) #constant-> 상수값으로 패딩
np.pad(x,(1,1), 'constant')

[[1 2 0]
 [3 4 0]
 [0 0 0]]


array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [20]:
# 'edge'-> 기존 배열 값으로 패딩

np.pad(x, (1,1), 'edge')

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [ ]:
# 그외 최대, 최소, 평균, 중앙값도 사용 가능

### 자료형 이해
chap.6

In [22]:
# dtype 클래스 알아보기
d= np.dtype(np.int32)

a= np.array([1,2,3,4], dtype=d)
print(a, a.dtype)
# 그외 다양한 자료형 클래스명 존재

[1 2 3 4] int32


### 날짜 자료형

In [23]:
# np.datetime64
ym=np.datetime64('2018-11')
print(ym, ym.dtype)
ymd= np.datetime64('2018-11-15')
print(ymd, ymd.dtype)

2018-11 datetime64[M]
2018-11-15 datetime64[D]


In [24]:
# 배열로 변경 및 날짜간 연산도 가능

a= np.array(['1018-11-15', '2018-12-15', '2010-01-15'],
            dtype= np.datetime64)
delta= np.datetime64('2018-11-15')-np.datetime64('2016-11-15')
print( delta, delta.dtype)

730 days timedelta64[D]


In [25]:
# 문자 자료형
# 유니코드와 바이트
np.str is str, np.unicode is str

np.str_ is str, np.unicode_ is str

np.str_ is bytes, np.unicode_ is bytes
#future warning

C:\Users\KDP-25\AppData\Local\Temp\ipykernel_14920\2742972441.py:3: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  np.str is str, np.unicode is str


AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [26]:
# 바이트 문자열 처리
# dtype= 'S'

a= np.array([['a', 'b'], ['c', 'd']], dtype='S')
print(a, a[0,0])


[[b'a' b'b']
 [b'c' b'd']] b'a'


In [ ]:
# 문자열 처리-> dtype=>  'U', np_str_ 등으로 처리 가능



### 시각화와 수학 함수
Chap.7

### 활성화 함수 그래프로 그리기

In [27]:
# 항등함수( y=x)


In [28]:
# 계단 함수 -> 결과가 0 또는 1(x가 0보다 클때 1)

In [29]:
# 하이퍼볼릭 탄젠트 함수
# 0 중심으로 대칭
# y= (e^x - e^-x)/ (e^x + e^-x)

In [30]:
# 시그모이드 함수
# y= 1/(1 + e^x)

In [ ]:
# 렐루 함수
# y=  0 (x<=0)
#     x (x>0)

In [ ]:
# 소프트맥스 함수
# y= exp(x)/ sum(exp(x))

### 수학 함수
chap.8

In [62]:
# 소수점 처리
# 버리기-> fix, trunc
a=np.array([3.14, 4.52])
print(np.fix(a))
# 올림, 버림->ceil, floor
print(np.ceil(a))
print(np.floor(a))
# 올림, 내림  (반올림)-> round, around
print(np.round(a,0))
print(np.around(a,0))

[3. 4.]
[4. 5.]
[3. 4.]
[3. 5.]
[3. 5.]


In [32]:
# mod, remainder-> 나머지
# divmod -> 몫과 나머지

In [33]:
# 부호, 절대값
# sign-> 부호 표시
# negative-> -곱하기
# abs, absolute ->절대값 

In [ ]:
# power-> 제곱
# sqrt-> 제곱근

### 논리 및 비교연산

In [34]:
# 논리 연산
# and, or, xor, ~, ^...

In [35]:
# 비교연산
# 당연한 것들

In [63]:
# 수열 합
# sum, cumsum(누적합)
a= np.arange(1,11)
print(np.sum(a))
print(np.cumsum(a))

55
[ 1  3  6 10 15 21 28 36 45 55]


In [37]:
# 수열 곱
# pord(수열, 축)-> 축에 따라 행 또는 열끼리 곱함
b= np.arange(1,11).reshape(2,5)
np.prod(b, axis=0)

array([ 6, 14, 24, 36, 50])

In [38]:
# cumprod(누적곱)
np.cumprod(b, axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6, 14, 24, 36, 50]])

In [ ]:
# 결측값 제외 계산
# nansum, nancumsum, nanprod, nancumprod
# -> nan을 합일때는 0, 곱일때는 1로 처리

In [64]:
# 자연 상수의 지수
# e, exp()
np.exp(0)
np.exp(-2)

0.1353352832366127

In [65]:
# 지수함수
x= np.arange(5)
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [68]:
# 로그함수 np.log()
x= np.arange(10000, 1000000, 100000)
np.ceil(np.log(x))

array([10., 12., 13., 13., 13., 14., 14., 14., 14., 14.])

In [69]:
# unique-> 유일한 원소 확인(중복된 원소는 제거)
x= np.array([[1,2,3], [4,5,6], [3,4,5]])
print(np.unique(x))
# np.in1d(원소, 배열) -> 원소 여부 확인
x= np.arange(5)
print(np.in1d(5,x), np.in1d(4,x))

[1 2 3 4 5 6]
[False] [ True]


In [41]:
# 합집합-> unionid()
# 교집합-> intersectid()
# 차집합-> unique()
# 대칭차집합 -> setdiffid()

In [42]:
# 삼각함수
# pi=180, sin, cos, tan

### 확률


In [ ]:
# 평균, 최대, 최소, 분산, 표편.... ddof=자유도 ->불편분산 구하기

# 표본-> 자유도=1

In [43]:
# 상관계수-> corr

# 공분산-> cov

### 방정식, 미적분, 합성곱
chap.10

In [44]:
# 다항식 -> poly1d 클래스로 객체 생성
# variable= 변수
# order= n

In [45]:
# 연립 방정식
# 행렬로 변환-> 
# ax+by=p =>a-b, x=p
# cx+dy=g =>d-d, y=g
# 를 행렬곱으로 계산
# 또는 역행렬 사용???

# 함수사용-> np.linalg.solve(a,b)
# lstsq -> pass

In [ ]:
# 배열 간의 차(이전항과 이후항의 차)
# np.diff(배열, 반복횟수(기본=1))

In [46]:
#diff로 미분
# 다항식 미분-> polyder 

In [47]:
# 중앙 차분으로 미분
# f(x)= (f(x+dx)-f(x-dx))/2dx
# 함수-> gradient()

In [48]:
# 적분 ->trapz



In [50]:
# 1차원 합성곱-> convovle(데이터, 필터, mode=)
# 2차원 합성곱-> scipy.sigmal-> signal.convolve2d()

In [51]:
# 필터링-> 항상 같은 배열 만듦

In [52]:
# 풀링-> 차원을 증가시켜 행과 열을 줄임

### 넘파이 특화 함수
chap.11

In [54]:
# 유니버설 함수 클래스 unfunc  ex)add
a=np.arange(10)
print(np.add.reduce(a))
print(a.sum())
print(np.add.reduceat(a, [0,4])) #시작점 부여
print(np.add.reduce(a[:4]))
print(np.add.reduce(a[4:]))
# + 직접 함수를 정의해서 사용도 가능

45
45
[ 6 39]
6
39


In [55]:
# vectorize 함수-> 다차원 배열 계산

In [56]:
# 함수를 전달받아서 배열 생성
# fromfunction(lambda...)

In [57]:
# 파일 처리
# .tofile() = np.save()
# .fromfile() = np.load()

# savetxt, loadtxt

In [ ]:
# 직렬화 처리 -> 객체를 그대로 저장