#### Tensor 변환
- 공유(sharing): .as_tensor(), .from_numpy()
- 복사(copy): .tensor(), .Tensor()

In [1]:
import torch

In [4]:
# python-> Tensor
# [1] list
# .as_tensor
data= list(range(1,10))

dataTS=torch.as_tensor(data, dtype=torch.int8)
dataTS.dtype, dataTS.ndim, dataTS.shape

(torch.int8, 1, torch.Size([9]))

In [10]:
# [2] Numpy ndarray
import numpy as np

In [13]:
# .as_tensor()

# Converts data into a tensor, sharing data and preserving autograd history if possible.
# 데이터를 공유함 (기본)

# but, if data is a tensor with a different dtype or device 
#                                               then it's copied as if using data.to(dtype=dtype, device=device).
# dtype or dvice가 다를 경우에는 카피
arr1= np.array([1,2,3])
print(arr1, arr1.shape, arr1.dtype, arr1.ndim)
arrTS= torch.as_tensor(arr1)
arr1[0]=77
arrTS[2]=100
arrTS, arr1

[1 2 3] (3,) int32 1


(tensor([ 77,   2, 100], dtype=torch.int32), array([ 77,   2, 100]))

In [23]:
#from_numpy
arr1=np.array([[5,7,9], [1,2,3]], dtype=np.float32) 

print(f'데이터 저장 메모리: {arr1.data}')
print(f'원소/요소 개수: {arr1.size}')
print(f'원소/요소 1개 크기: {arr1.data}')
print(f'타입: {arr1.dtype}')
print(f'방향: {arr1.strides}') #-> 개당 4bytes, 다음 행으로 넘어가는데 12bytes

데이터 저장 메모리: <memory at 0x0000020A13B2A040>
원소/요소 개수: 6
원소/요소 1개 크기: <memory at 0x0000020A13B2A040>
타입: float32
방향: (12, 4)


In [26]:
arrTS=torch.from_numpy(arr1)
# The returned tensor and ndarray share the same memory
# 새로운 텐서 생성(복사)
arrTS

tensor([[5., 7., 9.],
        [1., 2., 3.]])