#### Tensor의 모양/형태/shape 변경과 view Tensor


In [2]:
import torch
import numpy as np

In [3]:
dataTS= torch.arange(1,21)
dataTS, dataTS.shape, dataTS.stride()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 torch.Size([20]),
 (1,))

In [4]:
# shape 변경
# returns a view if shape is compatible with the current shape
# 같은 타입, 디바이스인 경우 self반환환
dataTS2=dataTS.reshape((-1,5))
dataTS2[0][0]=77

In [5]:
dataTS, dataTS2.untyped_storage()

(tensor([77,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
  77
  0
  0
  0
  0
  0
  0
  0
  2
  0
  0
  0
  0
  0
  0
  0
  3
  0
  0
  0
  0
  0
  0
  0
  4
  0
  0
  0
  0
  0
  0
  0
  5
  0
  0
  0
  0
  0
  0
  0
  6
  0
  0
  0
  0
  0
  0
  0
  7
  0
  0
  0
  0
  0
  0
  0
  8
  0
  0
  0
  0
  0
  0
  0
  9
  0
  0
  0
  0
  0
  0
  0
  10
  0
  0
  0
  0
  0
  0
  0
  11
  0
  0
  0
  0
  0
  0
  0
  12
  0
  0
  0
  0
  0
  0
  0
  13
  0
  0
  0
  0
  0
  0
  0
  14
  0
  0
  0
  0
  0
  0
  0
  15
  0
  0
  0
  0
  0
  0
  0
  16
  0
  0
  0
  0
  0
  0
  0
  17
  0
  0
  0
  0
  0
  0
  0
  18
  0
  0
  0
  0
  0
  0
  0
  19
  0
  0
  0
  0
  0
  0
  0
  20
  0
  0
  0
  0
  0
  0
  0
 [torch.storage.UntypedStorage(device=cpu) of size 160])

In [6]:
dataTS22= dataTS2.reshape((-1, 2))
dataTS22

print(dataTS22, dataTS22.shape, dataTS22.stride())
dataTS22.is_contiguous()

tensor([[77,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]) torch.Size([10, 2]) (2, 1)


True

In [11]:
dataTS23= dataTS22.T
dataTS23.is_contiguous(), dataTS23

(False,
 tensor([[77,  3,  5,  7,  9, 11, 13, 15, 17, 19],
         [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]]))

In [12]:
# 불연속적 -> 연속적으로 저장되도록 (메모리상으로)
DTS= dataTS23.contiguous()
DTS, DTS.is_contiguous()

(tensor([[77,  3,  5,  7,  9, 11, 13, 15, 17, 19],
         [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]]),
 True)