#### Tensor 이해

In [1]:
import torch

- tensor 생성 [2]

In [8]:
# .rand()
# -> 0<= ~ 1< 범위의 임의의 숫자 1개 추출
# *size -> 가변인자
torch.manual_seed(1)

dataTs1=torch.rand(1)           #1d
dataTs2=torch.rand(1,2)         #2d
dataT3= torch.rand(1,2,3)       #3d
dataTs1, dataTs2, dataT3

(tensor([0.7576]),
 tensor([[0.2793, 0.4031]]),
 tensor([[[0.7347, 0.0293, 0.7999],
          [0.3971, 0.7544, 0.5695]]]))

In [10]:
# .randn()

dataTs1=torch.randn(1)           #1d
dataTs2=torch.randn(1,2)         #2d
dataT3= torch.randn(1,2,3)       #3d
dataTs1, dataTs2, dataT3

(tensor([0.5773]),
 tensor([[-1.7637,  0.2264]]),
 tensor([[[-0.2355,  0.3019, -0.2770],
          [ 0.4771, -0.1103,  0.2913]]]))

In [15]:
# .randint()

data_ts=torch.randint(1,5,(3,5))
data_ts1= torch.randint(1,46,(4,6))
data_ts, data_ts1

(tensor([[2, 1, 1, 3, 1],
         [2, 3, 4, 1, 2],
         [4, 2, 1, 3, 1]]),
 tensor([[32, 25,  2, 36, 33, 33],
         [13, 14,  4, 19, 36, 40],
         [44, 15, 40, 40, 29,  1],
         [19, 35, 42,  1, 36, 24]]))

In [ ]:
# .OOOtensor()
# - 특정 타입으로 tensor 생성