#### Tensor 이해-> 형변환


In [1]:
import torch

In [7]:
# [1] .type()

dataTS1= torch.tensor([1,3,5])
print(dataTS1, dataTS1.dtype)

#type
dataTS11= dataTS1.type(torch.float32)
dataTS11, dataTS11.dtype

tensor([1, 3, 5]) torch.int64


(tensor([1., 3., 5.]), torch.float32)

In [11]:
# [2] .타입명()
dataTS1.bool()


tensor([True, True, True])

In [14]:
# [3] to(dtype, device)
dataTS1.to(dtype=torch.int8,
           device='cuda' if torch.cuda.is_available() else 'cpu')

tensor([1, 3, 5], dtype=torch.int8)

In [15]:
# 인덱싱, 슬라이싱, 연산(+행렬 연산) -> python과 동일