#### Tensor 이해

In [3]:
import torch

In [4]:
# Data Type을 설정 후 생성
# - 데이터 사이즈 설정, 자료형 변환시 사용

In [5]:
# 정수형
data=[1.4,2.8,3.1]

dataTS1= torch.CharTensor(data)
print(dataTS1)
# 또는
dataTS2= torch.tensor(data, dtype=torch.int8)
dataTS2

tensor([1, 2, 3], dtype=torch.int8)


C:\Users\KDP-25\AppData\Local\Temp\ipykernel_16276\420880271.py:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1= torch.CharTensor(data)
C:\Users\KDP-25\AppData\Local\Temp\ipykernel_16276\420880271.py:7: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS2= torch.tensor(data, dtype=torch.int8)


tensor([1, 2, 3], dtype=torch.int8)

In [6]:
# 논리형(bool타입)
data=[1.4,2.8,3.1]

dataTS1= torch.BoolTensor(data)
print(dataTS1)
# 또는
dataTS2= torch.tensor(data, dtype=torch.bool)
dataTS2
#bool -> 0만 false

tensor([True, True, True])


tensor([True, True, True])

In [7]:
# 실수형
data=[1.4,2.8,3.1]

dataTS1= torch.DoubleTensor(data)
print(dataTS1)
# 또는
dataTS2= torch.tensor(data, dtype=torch.double)
dataTS2
#bool -> 0만 false

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)


tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)

- Tensor 저장 및 실행 위치 설정-> device 속성 설정

In [11]:
# 실행 위치-> CPU, GPU
DEVICE= 'cuda' if torch.cuda.is_available() else 'cpu'
DEVICE

'cpu'

In [12]:
# .anrange() 시작, 끝, 개수